In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [57]:
df = pd.read_csv('titanic_data_set.csv')
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    object
 2   Pclass       891 non-null    object
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(3), object(7)
memory usage: 83.7+ KB

In [59]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

***Deleting Unnecessary Features***

In [60]:
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)
df.head(5)

  Survived Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0       no  third    male  22.0      1      0   7.2500   NaN        S
1      yes  first  female  38.0      1      0  71.2833   C85        C
2      yes  third  female  26.0      0      0   7.9250   NaN        S
3      yes  first  female  35.0      1      0  53.1000  C123        S
4       no  third    male  35.0      0      0   8.0500   NaN        S

***separating features and target columns***

In [61]:
# features 
x = df.drop(['Survived'], axis=1)

In [62]:
# target 
y = df['Survived']

***Train Test Split***

In [63]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

***Imputing Missing Values***

***Neumerical Values***

In [64]:
x_train.isnull().sum()

Pclass        0
Sex           0
Age         140
SibSp         0
Parch         0
Fare          0
Cabin       553
Embarked      2
dtype: int64

***By Pandas***

***Mean Impute***

In [65]:
# age
age_mean = x_train['Age'].mean()
x_train['Age'].fillna(age_mean)

# fare
fare_mean = x_train['Fare'].mean()
x_train['Fare'].fillna(fare_mean)

331     28.5000
733     13.0000
382      7.9250
704      7.8542
813     31.2750
         ...
106      7.6500
270     31.0000
860     14.1083
435    120.0000
102     77.2875
Name: Fare, Length: 712, dtype: float64

In [66]:
# age
age_mean = x_test['Age'].mean()
x_test['Age'].fillna(age_mean)

# fare
fare_mean = x_test['Fare'].mean()
x_test['Fare'].fillna(fare_mean)

709    15.2458
439    10.5000
840     7.9250
720    33.0000
39     11.2417
        ...
433     7.1250
773     7.2250
25     31.3875
84     10.5000
10     16.7000
Name: Fare, Length: 179, dtype: float64

***Simple Imputor of Numerical Values***

In [67]:
# Age (by mean)
age_imputor = SimpleImputer(missing_values=np.nan, strategy='mean')

age_imputor.fit(x_train[['Age']])

x_train['Age'] = age_imputor.transform(x_train[['Age']]).ravel()
x_test['Age'] = age_imputor.transform(x_test[['Age']]).ravel()

***Simple Imputor of Categrical Values***

In [68]:
# Embarked
embarked_imputor = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

embarked_imputor.fit(x_train[['Embarked']])

x_train['Embarked'] = embarked_imputor.transform(x_train[['Embarked']]).ravel()
x_test['Embarked'] = embarked_imputor.transform(x_test[['Embarked']]).ravel()

In [69]:
# Cabin
cabin_imputor = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='Missing', add_indicator=True)

cabin_imputor.fit(x_train[['Cabin']])

x_train[['Cabin', 'missing_indicator']] = cabin_imputor.transform(x_train[['Cabin']])
x_test[['Cabin', 'missing_indicator']] = cabin_imputor.transform(x_test[['Cabin']])

In [70]:
df.sample(3)

    Survived Pclass   Sex   Age  SibSp  Parch   Fare Cabin Embarked
94        no  third  male  59.0      0      0  7.250   NaN        S
200       no  third  male  28.0      0      0  9.500   NaN        S
115       no  third  male  21.0      0      0  7.925   NaN        S

In [71]:
x_train.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,missing_indicator
216,third,female,27.000000,0,0,7.9250,Missing,S,True
533,third,female,29.498846,0,2,22.3583,Missing,C,True
249,second,male,54.000000,1,0,26.0000,Missing,S,True

# Encoding

***Ordinal Encoding***

In [72]:
from sklearn.preprocessing import OrdinalEncoder

**Pclass**

In [73]:
pclass_encoder = OrdinalEncoder(categories=[['third', 'second', 'first']])

pclass_encoder.fit(x_train[['Pclass']])

# transform
x_train['encoded_Pclass'] = pclass_encoder.transform(x_train[['Pclass']]).ravel()
x_test['encoded_Pclass'] = pclass_encoder.transform(x_test[['Pclass']]).ravel()

In [74]:
x_train.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,missing_indicator,encoded_Pclass
737,first,male,35.000000,0,0,512.3292,B101,C,False,2.0
295,first,male,29.498846,0,0,27.7208,Missing,C,True,2.0
127,third,male,24.000000,0,0,7.1417,Missing,S,True,0.0

In [75]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,missing_indicator,encoded_Pclass
174,first,male,56.000000,0,0,30.6958,A7,C,False,2.0
837,third,male,29.498846,0,0,8.0500,Missing,S,True,0.0
136,first,female,19.000000,0,2,26.2833,D47,S,False,2.0

***One Hot Encoding***

In [76]:
from sklearn.preprocessing import OneHotEncoder

**Gender**

In [77]:
sex_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas') 

sex_encoder.fit(x_train[['Sex']])

# transform
ohe_df_train = sex_encoder.transform(x_train[['Sex']])
ohe_df_test = sex_encoder.transform(x_test[['Sex']])

# concatenate
x_train = pd.concat([x_train, ohe_df_train], axis=1)
x_test = pd.concat([x_test, ohe_df_test], axis=1)

**Embarked**

In [78]:
embarked_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

embarked_encoder.fit(x_train[['Embarked']])

# transform
ohe_df_train = embarked_encoder.transform(x_train[['Embarked']])
ohe_df_test = embarked_encoder.transform(x_test[['Embarked']])

# concatenate
x_train = pd.concat([x_train, ohe_df_train], axis=1)
x_test = pd.concat([x_test, ohe_df_test], axis=1)

In [79]:
x_train.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
544,first,male,50.000000,1,0,106.425,C86,C,False,2.0,0.0,1.0,1.0,0.0,0.0
185,first,male,29.498846,0,0,50.000,A32,S,False,2.0,0.0,1.0,0.0,0.0,1.0
671,first,male,31.000000,1,0,52.000,B71,S,False,2.0,0.0,1.0,0.0,0.0,1.0

In [80]:
x_test.sample(3)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
659,first,male,58.0,0,2,113.2750,D48,C,False,2.0,0.0,1.0,1.0,0.0,0.0
876,third,male,20.0,0,0,9.8458,Missing,S,True,0.0,0.0,1.0,0.0,0.0,1.0
670,second,female,40.0,1,1,39.0000,Missing,S,True,1.0,1.0,0.0,0.0,0.0,1.0

**Drop**

In [81]:
x_train.drop(['Pclass', 'Sex', 'Embarked'], axis=1, inplace=True)
x_train.sample(3)

,Age,SibSp,Parch,Fare,Cabin,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
40,40.0,1,0,9.475,Missing,True,0.0,1.0,0.0,0.0,0.0,1.0
190,32.0,0,0,13.000,Missing,True,1.0,1.0,0.0,0.0,0.0,1.0
429,32.0,0,0,8.050,E10,False,0.0,0.0,1.0,0.0,0.0,1.0

In [82]:
x_test.drop(['Pclass', 'Sex', 'Embarked'], axis=1, inplace=True)
x_test.sample(3)

,Age,SibSp,Parch,Fare,Cabin,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
110,47.000000,0,0,52.00,C110,False,2.0,0.0,1.0,0.0,0.0,1.0
790,29.498846,0,0,7.75,Missing,True,0.0,0.0,1.0,0.0,1.0,0.0
357,38.000000,0,0,13.00,Missing,True,1.0,1.0,0.0,0.0,0.0,1.0

***Cabin***

In [83]:
x_train['Cabin'].value_counts()

Cabin
Missing        553
C23 C25 C27      4
B96 B98          3
G6               3
C22 C26          3
              ...
C104             1
D11              1
C86              1
C7               1
C62 C64          1
Name: count, Length: 118, dtype: int64

In [84]:
x_train['Cabin_Deck'] = x_train['Cabin'].astype(str).str[0]
x_test['Cabin_Deck'] = x_test['Cabin'].astype(str).str[0]

In [85]:
x_train['Cabin_Deck'].value_counts()

Cabin_Deck
M    553
C     52
B     38
E     24
D     19
F     12
A     10
G      3
T      1
Name: count, dtype: int64

In [86]:
x_test['Cabin_Deck'].value_counts()

Cabin_Deck
M    134
D     14
B      9
E      8
C      7
A      5
F      1
G      1
Name: count, dtype: int64

In [87]:
# one hot encoding
cabin_encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

cabin_encoder.fit(x_train[['Cabin_Deck']])

# transform
ohe_df_train = cabin_encoder.transform(x_train[['Cabin_Deck']])
ohe_df_test = cabin_encoder.transform(x_test[['Cabin_Deck']])

# concatenate
x_train = pd.concat([x_train, ohe_df_train], axis=1)
x_test = pd.concat([x_test, ohe_df_test], axis=1)

In [88]:
x_train.drop(['Cabin'], axis=1, inplace=True)
x_train.sample(3)

,Age,SibSp,Parch,Fare,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,Cabin_Deck,Cabin_Deck_A,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_M,Cabin_Deck_T
755,0.67,1,1,14.5000,True,1.0,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
848,28.00,0,1,33.0000,True,1.0,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
838,32.00,0,0,56.4958,True,0.0,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [89]:
x_test.drop(['Cabin'], axis=1, inplace=True)
x_test.sample(3)

,Age,SibSp,Parch,Fare,missing_indicator,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,Cabin_Deck,Cabin_Deck_A,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_M,Cabin_Deck_T
109,29.498846,1,0,24.15,True,0.0,1.0,0.0,0.0,1.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
853,16.000000,0,1,39.40,False,2.0,1.0,0.0,0.0,0.0,...,D,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70,32.000000,0,0,10.50,True,1.0,0.0,1.0,0.0,0.0,...,M,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

***Label Encoding***

In [90]:
from sklearn.preprocessing import LabelEncoder

In [91]:
y_train.sample(3)

74     yes
440    yes
562     no
Name: Survived, dtype: object

In [92]:
le = LabelEncoder()

# fit
le.fit(y_train)

# transform
encoded_Ytrain = le.transform(y_train)
encoded_Ytest = le.transform(y_test)

In [93]:
encoded_Ytrain

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0])

In [94]:
encoded_Ytest

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1])

In [95]:
encoded_Ytrain = pd.Series(encoded_Ytrain, index=y_train.index)
encoded_Ytrain.sample(3)

603    0
175    0
495    0
dtype: int64

In [96]:
encoded_Ytest = pd.Series(encoded_Ytest, index=y_test.index)
encoded_Ytest.sample(3)

396    0
604    1
889    1
dtype: int64